import { wrap } from "comlink";
import type { ComputeApi } from "./api";

let workerInstance: Worker | null = null;
let apiProxy: ComputeApi | null = null;

export function getComputeWorker(): ComputeApi {
  if (!apiProxy) {
    throw new Error("Worker not initialized. Call initWorker() first.");
  }
  return apiProxy;
}

export async function initWorker(): Promise<ComputeApi> {
  if (apiProxy) return apiProxy;

  workerInstance = new Worker(new URL("./compute.worker.ts", import.meta.url), {
    type: "module",
  });

  apiProxy = wrap<ComputeApi>(workerInstance);

  // Initialize WASM inside the worker.
  // The pkg directory is generated by wasm-pack at crates/choco-wasm/pkg/.
  // Vite resolves this relative to the project root during dev/build.
  const wasmUrl = new URL(
    "/crates/choco-wasm/pkg/choco_wasm.js",
    import.meta.url
  ).href;

  await apiProxy.init({ wasmUrl });

  return apiProxy;
}

export function terminateWorker(): void {
  if (workerInstance) {
    workerInstance.terminate();
    workerInstance = null;
    apiProxy = null;
  }
}
